-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('ab-wheel-rollout', 'Ab Wheel Rollout'),
  ('air-bike', 'Air Bike'),
  ('archer-pull-ups', 'Archer Pull Ups'),
  ('archer-push-ups', 'Archer Push Ups'),
  ('arnold-press', 'Arnold Press'),
  ('assisted-dips', 'Machine Assisted Dips'),
  ('assisted-pull-ups', 'Assisted Pull Ups'),
  ('back-extension', 'Back Extension'),
  ('back-lever', 'Back Lever'),
  ('ball-leg-curl', 'Stability Ball Leg Curl'),
  ('ball-pike', 'Ball Pike'),
  ('band-assisted-pull-ups', 'Band Assisted Pull Ups'),
  ('band-pull-apart', 'Band Pull Apart'),
  ('banded-adductor-stretch', 'Banded Adductor Stretch'),
  ('banded-ankle-stretch', 'Banded Ankle Stretch'),
  ('banded-calf-stretch', 'Banded Calf Stretch'),
  ('banded-chest-stretch', 'Banded Chest Stretch'),
  ('banded-clamshell', 'Banded Clamshell'),
  ('banded-figure-4-stretch', 'Banded Figure-4 Stretch'),
  ('banded-fire-hydrant', 'Banded Fire Hydrant'),
  ('banded-glute-bridge', 'Banded Glute Bridge'),
  ('banded-good-morning', 'Banded Good Morning'),
  ('banded-hamstring-stretch', 'Banded Hamstring Stretch'),
  ('banded-hip-thrust', 'Banded Hip Thrust'),
  ('banded-it-band-stretch', 'Banded IT-Band Stretch'),
  ('banded-kneeling-hip-thrust', 'Banded Kneeling Hip Thrust'),
  ('banded-lat-stretch', 'Banded Lat Stretch'),
  ('banded-lateral-walk', 'Banded Lateral Walk'),
  ('banded-rear-delt-stretch', 'Banded Rear Delt Stretch'),
  ('banded-romanian-deadlift', 'Banded Romanian Deadlift'),
  ('banded-seated-hip-abduction', 'Banded Seated Hip Abduction'),
  ('banded-shoulder-stretch', 'Banded Shoulder Stretch'),
  ('banded-squat', 'Banded Squat'),
  ('banded-standing-curl', 'Banded Standing Leg Curl'),
  ('banded-standing-hip-abduction', 'Banded Standing Hip Abduction'),
  ('banded-standing-hip-adduction', 'Banded Standing Hip Adduction'),
  ('banded-sumo-walk', 'Banded Sumo Walk'),
  ('banded-terminal-knee-extension', 'Banded Terminal Knee Extension'),
  ('banded-triceps-stretch', 'Banded Triceps Stretch'),
  ('barbell-ab-rollout', 'Barbell Ab Rollout'),
  ('barbell-calf-raise', 'Barbell Calf Raise'),
  ('barbell-curl', 'Barbell Curl'),
  ('barbell-front-raise', 'Barbell Front Raise'),
  ('barbell-glute-bridge', 'Barbell Glute Bridge'),
  ('barbell-lunge', 'Barbell Lunge'),
  ('barbell-overhead-extension', 'Barbell Overhead Extension'),
  ('barbell-preacher-curl', 'Barbell Preacher Curl'),
  ('barbell-pullover', 'Barbell Pullover'),
  ('barbell-rear-delt-row', 'Barbell Rear Delt Row'),
  ('barbell-reverse-lunge', 'Barbell Reverse Lunge'),
  ('barbell-row', 'Bent-Over Barbell Row'),
  ('barbell-wrist-curl', 'Barbell Wrist Curl'),
  ('battle-rope-double-slam', 'Battle Rope Double Slam'),
  ('battle-ropes', 'Battle Ropes'),
  ('bear-crawl', 'Bear Crawl'),
  ('behind-the-back-barbell-shrug', 'Behind the Back Barbell Shrug'),
  ('behind-the-neck-lat-pulldown', 'Behind-the-Neck Lat Pulldown'),
  ('behind-the-neck-press', 'Behind the Neck Press'),
  ('behind-the-neck-pull-ups', 'Behind-the-Neck Pull-Up'),
  ('bench-adductor-stretch', 'Bench Adductor Stretch'),
  ('bench-ankle-stretch', 'Bench Ankle Stretch'),
  ('bench-bulgarian-split-stretch', 'Bench Bulgarian Split Stretch'),
  ('bench-calf-stretch', 'Bench Calf Stretch'),
  ('bench-chest-stretch', 'Bench Chest Stretch'),
  ('bench-childs-pose', 'Bench Child''s Pose'),
  ('bench-couch-stretch', 'Bench Couch Stretch'),
  ('bench-dips', 'Bench Dips'),
  ('bench-figure-4-glute-stretch', 'Bench Figure-4 Glute Stretch'),
  ('bench-hamstring-stretch', 'Bench Hamstring Stretch'),
  ('bench-lat-stretch', 'Bench Lat Stretch'),
  ('bench-leg-pull-in', 'Bench Leg Pull-In'),
  ('bench-press', 'Barbell Bench Press'),
  ('bench-pull', 'Bench Pull'),
  ('bent-arm-barbell-pullover', 'Bent Arm Barbell Pullover'),
  ('bent-arm-ez-bar-pullover', 'Bent-Arm EZ-Bar Pullover'),
  ('bent-over-db-row', 'Bent-Over Dumbbell Row'),
  ('bent-over-ez-bar-row', 'Bent-Over EZ-Bar Row'),
  ('bicep-curl', 'Dumbbell Bicep Curl'),
  ('bicycle-crunch', 'Bicycle Crunch'),
  ('bird-dog', 'Bird-Dog'),
  ('bird-dog-hold', 'Bird Dog Hold'),
  ('boat-pose', 'Boat Pose'),
  ('bodyweight-calf-raise', 'Bodyweight Calf Raise'),
  ('bodyweight-good-morning', 'Bodyweight Good Morning'),
  ('bodyweight-lateral-raise', 'Bodyweight Lateral Raise'),
  ('bodyweight-overhead-press', 'Bodyweight Overhead Press'),
  ('bodyweight-reverse-lunge', 'Bodyweight Reverse Lunge'),
  ('bodyweight-squat', 'Bodyweight Squat'),
  ('bow-pose', 'Bow Pose'),
  ('box-jump', 'Box Jump'),
  ('box-squat', 'Box Squat'),
  ('bulgarian-split-squat', 'Bulgarian Split Squat'),
  ('burpees', 'Burpees'),
  ('butterfly-stretch', 'Butterfly Stretch'),
  ('cable-bent-over-row', 'Cable Bent-Over Row'),
  ('cable-chest-press', 'Cable Chest Press'),
  ('cable-crunch', 'Cable Crunch'),
  ('cable-curl', 'Cable Curl'),
  ('cable-external-rotation', 'Cable External Rotation'),
  ('cable-fly', 'Cable Fly')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('cable-front-raise', 'Cable Front Raise'),
  ('cable-hammer-curl', 'Cable Hammer Curl'),
  ('cable-kickback', 'Cable Glute Kickback'),
  ('cable-lateral-raise', 'Cable Lateral Raise'),
  ('cable-pallof-press', 'Cable Pallof Press'),
  ('cable-tricep-kickback', 'Cable Tricep Kickback'),
  ('cable-upright-row', 'Cable Upright Row'),
  ('cable-wrist-curl', 'Cable Wrist Curl'),
  ('camel-pose', 'Camel Pose'),
  ('captains-chair-knee-raise', 'Captain''s Chair Knee Raise'),
  ('captains-chair-leg-raise', 'Captain''s Chair Leg Raise'),
  ('cat-cow', 'Cat-Cow'),
  ('cat-stretch', 'Cat Stretch'),
  ('chair-pose', 'Chair Pose'),
  ('cheat-curl', 'Cheat Curl'),
  ('chest-press-machine', 'Machine Chest Press'),
  ('chest-supported-db-row', 'Chest-Supported Dumbbell Row'),
  ('chest-supported-dumbbell-shrug', 'Chest Supported Dumbbell Shrug'),
  ('chest-supported-kettlebell-row', 'Chest-Supported Kettlebell Row'),
  ('chest-supported-smith-machine-row', 'Chest-Supported Smith Machine Row'),
  ('childs-pose', 'Child''s Pose'),
  ('chin-tuck-hold', 'Chin Tuck Hold'),
  ('chin-ups', 'Chin-Ups'),
  ('clamshells', 'Clamshells'),
  ('clamshells-hold', 'Clamshell Hold'),
  ('clap-push-ups', 'Clap Push-Ups'),
  ('clean', 'Clean'),
  ('clean-and-jerk', 'Clean and Jerk'),
  ('close-grip-barbell-curl', 'Close-Grip Barbell Curl'),
  ('close-grip-bench-press', 'Close-Grip Bench Press'),
  ('close-grip-db-bench-press', 'Close-Grip Dumbbell Bench Press'),
  ('close-grip-ez-bar-bench-press', 'Close-Grip EZ-Bar Bench Press'),
  ('close-grip-ez-bar-curl', 'Close-Grip EZ-Bar Curl'),
  ('close-grip-incline-bench', 'Close-Grip Incline Bench Press'),
  ('close-grip-lat-pulldown', 'Close Grip Lat Pulldown'),
  ('close-grip-pull-ups', 'Close-Grip Pull-Ups'),
  ('close-grip-push-ups', 'Close Grip Push Ups'),
  ('close-stance-leg-press', 'Close-Stance Leg Press'),
  ('cobra-stretch', 'Cobra Stretch'),
  ('cocoons', 'Cocoons'),
  ('concentration-curl', 'Concentration Curl'),
  ('cossack-squat', 'Cossack Squat'),
  ('cow-face-pose', 'Cow Face Pose'),
  ('crab-dips', 'Crab Dips'),
  ('crescent-lunge', 'Crescent Lunge'),
  ('cross-body-crunch', 'Cross-Body Crunch'),
  ('cross-body-hammer-curl', 'Cross Body Hammer Curl'),
  ('cross-body-shoulder-stretch', 'Cross-Body Shoulder Stretch'),
  ('crow-pose', 'Crow Pose'),
  ('crunches', 'Crunches'),
  ('dancer-pose', 'Dancer Pose'),
  ('db-bench-press', 'Dumbbell Bench Press'),
  ('db-fly', 'Dumbbell Fly'),
  ('db-kickstand-deadlift', 'Dumbbell Kickstand Deadlift'),
  ('db-lunge', 'Dumbbell Lunge'),
  ('db-overhead-carry', 'Dumbbell Overhead Carry'),
  ('db-pullover', 'Dumbbell Pullover'),
  ('db-reverse-curl', 'Dumbbell Reverse Curl'),
  ('db-reverse-wrist-curl', 'Dumbbell Reverse Wrist Curl'),
  ('db-shrug', 'Dumbbell Shrug'),
  ('db-skull-crusher', 'Dumbbell Skull Crusher'),
  ('db-somersault-squat', 'Dumbbell Somersault Squat'),
  ('db-squat', 'Dumbbell Squat'),
  ('db-sumo-squat', 'Dumbbell Sumo Squat'),
  ('db-svend-press', 'Dumbbell Svend Press'),
  ('dead-bug', 'Dead Bug'),
  ('dead-bug-hold', 'Dead Bug Hold'),
  ('dead-hang', 'Dead Hang'),
  ('deadlift', 'Barbell Deadlift'),
  ('decline-bench-press', 'Decline Bench Press'),
  ('decline-bench-press-barbell', 'Decline Barbell Bench Press'),
  ('decline-bench-press-ez-bar', 'Decline EZ-Bar Bench Press'),
  ('decline-crunch', 'Decline Crunch'),
  ('decline-db-fly', 'Decline Dumbbell Fly'),
  ('decline-push-up', 'Decline Push-Up'),
  ('deficit-deadlift', 'Deficit Deadlift'),
  ('deficit-push-ups', 'Deficit Push Ups'),
  ('diamond-push-ups', 'Diamond Push Ups'),
  ('dips', 'Chest Dips'),
  ('dolphin-pose', 'Dolphin Pose'),
  ('donkey-calf-raise', 'Donkey Calf Raise'),
  ('doorway-chest-stretch', 'Doorway Chest Stretch'),
  ('double-db-kickstand-deadlift', 'Double Dumbbell Kickstand Deadlift'),
  ('double-db-overhead-carry', 'Double Dumbbell Overhead Carry'),
  ('double-kettlebell-bicep-curl', 'Double Kettlebell Bicep Curl'),
  ('double-kettlebell-clean', 'Double Kettlebell Clean'),
  ('double-kettlebell-clean-and-press', 'Double Kettlebell Clean and Press'),
  ('double-kettlebell-dead-clean', 'Double Kettlebell Dead Clean'),
  ('double-kettlebell-dead-split-snatch', 'Double Kettlebell Dead Split Snatch'),
  ('double-kettlebell-jerk', 'Double Kettlebell Jerk'),
  ('double-kettlebell-overhead-carry', 'Double Kettlebell Overhead Carry'),
  ('double-kettlebell-overhead-press', 'Double Kettlebell Overhead Press'),
  ('double-kettlebell-push-press', 'Double Kettlebell Push Press'),
  ('double-kettlebell-rear-delt-row', 'Double Kettlebell Rear Delt Row'),
  ('double-kettlebell-row', 'Double Kettlebell Row'),
  ('double-kettlebell-split-jerk', 'Double Kettlebell Split Jerk'),
  ('double-kettlebell-swing-snatch', 'Double Kettlebell Swing Snatch'),
  ('downward-dog', 'Downward-Facing Dog'),
  ('downward-dog-knee-tuck', 'Downward Dog Knee Tuck'),
  ('downward-dog-pedal', 'Downward Dog Pedal')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('downward-dog-to-knee-drive', 'Downward Dog to Knee Drive'),
  ('downward-dog-to-low-lunge', 'Downward Dog to Low Lunge'),
  ('downward-dog-to-plank', 'Downward Dog to Plank'),
  ('downward-dog-to-upward-dog', 'Downward Dog to Upward Dog'),
  ('drag-curl', 'Drag Curl'),
  ('dragon-flag', 'Dragon Flag'),
  ('dumbbell-bench-pull', 'Dumbbell Bench Pull'),
  ('dumbbell-calf-raise', 'Dumbbell Calf Raise'),
  ('dumbbell-deadlift', 'Dumbbell Deadlift'),
  ('dumbbell-face-pull', 'Dumbbell Face Pull'),
  ('dumbbell-farmers-walk', 'Dumbbell Farmer''s Walk'),
  ('dumbbell-floor-press', 'Dumbbell Floor Press'),
  ('dumbbell-front-raise', 'Dumbbell Front Raise'),
  ('dumbbell-front-squat', 'Dumbbell Front Squat'),
  ('dumbbell-hip-thrust', 'Dumbbell Hip Thrust'),
  ('dumbbell-pistol-squat', 'Dumbbell Pistol Squat'),
  ('dumbbell-push-press', 'Dumbbell Push Press'),
  ('dumbbell-reverse-fly', 'Dumbbell Reverse Fly'),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift'),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press'),
  ('dumbbell-side-bend', 'Dumbbell Side Bend'),
  ('dumbbell-snatch', 'Dumbbell Snatch'),
  ('dumbbell-split-squat', 'Dumbbell Split Squat'),
  ('dumbbell-tricep-extension', 'Dumbbell Tricep Extension'),
  ('dumbbell-upright-row', 'Dumbbell Upright Row'),
  ('dumbbell-windmill', 'Dumbbell Windmill'),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl'),
  ('eagle-pose', 'Eagle Pose'),
  ('easy-pose', 'Easy Pose'),
  ('elliptical-trainer', 'Elliptical Trainer'),
  ('extended-side-angle', 'Extended Side Angle Pose'),
  ('ez-bar-bench-press', 'EZ-Bar Bench Press'),
  ('ez-bar-curl', 'EZ-Bar Curl'),
  ('ez-bar-front-raise', 'EZ-Bar Front Raise'),
  ('ez-bar-lying-tricep-extension', 'EZ-Bar Lying Triceps Extension'),
  ('ez-bar-overhead-extension', 'EZ-Bar Overhead Tricep Extension'),
  ('ez-bar-pullover', 'EZ Bar Pullover'),
  ('ez-bar-reverse-curl', 'EZ-Bar Reverse Curl'),
  ('ez-bar-reverse-grip-row', 'EZ Bar Reverse Grip Row'),
  ('ez-bar-romanian-deadlift', 'EZ-Bar Romanian Deadlift'),
  ('ez-bar-shrug', 'EZ-Bar Shrug'),
  ('ez-bar-spider-curl', 'EZ Bar Spider Curl'),
  ('ez-bar-upright-row', 'EZ-Bar Upright Row'),
  ('ez-bar-wrist-curl', 'EZ-Bar Wrist Curl'),
  ('face-pull', 'Cable Face Pull'),
  ('fish-pose', 'Fish Pose'),
  ('floor-ez-bar-press', 'Floor EZ-Bar Press'),
  ('floor-kettlebell-pullover', 'Floor Kettlebell Pullover'),
  ('floor-press', 'Floor Press'),
  ('flutter-kicks', 'Flutter Kicks'),
  ('front-lever', 'Front Lever'),
  ('front-squat', 'Front Squat'),
  ('garland-pose', 'Garland Pose'),
  ('glute-bridge', 'Glute Bridge'),
  ('glute-bridge-hold', 'Glute Bridge Hold'),
  ('glute-kickback', 'Glute Kickback'),
  ('glute-kickback-hold', 'Glute Kickback Hold'),
  ('goblet-squat', 'Goblet Squat'),
  ('good-morning', 'Good Morning'),
  ('hack-squat', 'Hack Squat'),
  ('hack-squat-calf-raise', 'Hack Squat Calf Raise'),
  ('half-kneeling-hip-flexor-rock', 'Half-Kneeling Hip Flexor Rock'),
  ('half-moon-pose', 'Half Moon Pose'),
  ('hammer-curl', 'Dumbbell Hammer Curl'),
  ('handstand-push-ups', 'Handstand Push Ups'),
  ('hang-clean', 'Hang Clean'),
  ('hang-power-clean', 'Hang Power Clean'),
  ('hanging-knee-raise', 'Hanging Knee Raise'),
  ('hanging-leg-raise', 'Hanging Leg Raise'),
  ('hanging-pike', 'Hanging Pike'),
  ('happy-baby', 'Happy Baby Pose'),
  ('head-to-knee-pose', 'Head-to-Knee Pose'),
  ('heel-elevated-squat', 'Heel-Elevated Squat'),
  ('heel-to-toe-walk', 'Heel-to-Toe Walk'),
  ('hero-pose', 'Hero Pose'),
  ('hex-bar-deadlift', 'Hex Bar Deadlift'),
  ('high-foot-leg-press', 'High-Foot Leg Press'),
  ('high-knees', 'High Knees'),
  ('high-plank', 'High Plank'),
  ('hip-abduction', 'Machine Hip Abduction'),
  ('hip-adduction', 'Hip Adduction'),
  ('hip-thrust', 'Barbell Hip Thrust'),
  ('hollow-body-hold', 'Hollow Body Hold'),
  ('horizontal-leg-press', 'Horizontal Leg Press'),
  ('human-flag', 'Human Flag'),
  ('incline-bench-ez-bar-press', 'Incline EZ-Bar Bench Press'),
  ('incline-bench-press', 'Incline Barbell Bench Press'),
  ('incline-db-curl', 'Incline Dumbbell Curl'),
  ('incline-db-press', 'Incline Dumbbell Press'),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly'),
  ('incline-hammer-curl', 'Incline Hammer Curl'),
  ('incline-push-ups', 'Incline Push-Up'),
  ('incline-treadmill-walk', 'Incline Treadmill Walk'),
  ('inverted-row', 'Inverted Row'),
  ('isometric-neck-side', 'Isometric Neck Lateral Flexion'),
  ('jackknife-sit-up', 'Jackknife Sit-Up'),
  ('jefferson-curl', 'Jefferson Curl'),
  ('jump-rope', 'Jump Rope'),
  ('jump-squat', 'Jump Squat'),
  ('jumping-jacks', 'Jumping Jacks')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('kettlebell-bulgarian-split-squat', 'Kettlebell Bulgarian Split Squat'),
  ('kettlebell-close-grip-floor-press', 'Kettlebell Close-Grip Floor Press'),
  ('kettlebell-concentration-curl', 'Kettlebell Concentration Curl'),
  ('kettlebell-deadlift', 'Kettlebell Deadlift'),
  ('kettlebell-farmers-walk', 'Kettlebell Farmer''s Walk'),
  ('kettlebell-floor-press', 'Kettlebell Floor Press'),
  ('kettlebell-goblet-lunge', 'Kettlebell Goblet Lunge'),
  ('kettlebell-halo', 'Kettlebell Halo'),
  ('kettlebell-hammer-curl', 'Kettlebell Hammer Curl'),
  ('kettlebell-hip-thrust', 'Kettlebell Hip Thrust'),
  ('kettlebell-kickstand-deadlift', 'Kettlebell Kickstand Deadlift'),
  ('kettlebell-lunge-press', 'Kettlebell Lunge Press'),
  ('kettlebell-offset-reverse-lunge-and-press', 'Kettlebell Offset Reverse Lunge and Press'),
  ('kettlebell-overhead-carry', 'Kettlebell Overhead Carry'),
  ('kettlebell-overhead-tricep-extension', 'Kettlebell Overhead Tricep Extension'),
  ('kettlebell-pistol-squat', 'Kettlebell Pistol Squat'),
  ('kettlebell-pullover', 'Kettlebell Pullover'),
  ('kettlebell-reverse-lunge', 'Kettlebell Reverse Lunge'),
  ('kettlebell-reverse-wrist-curl', 'Kettlebell Reverse Wrist Curl'),
  ('kettlebell-rotational-lunge', 'Kettlebell Rotational Lunge'),
  ('kettlebell-russian-twist', 'Kettlebell Russian Twist'),
  ('kettlebell-shrug', 'Kettlebell Shrug'),
  ('kettlebell-single-leg-deadlift', 'Kettlebell Single Leg Deadlift'),
  ('kettlebell-skull-crusher', 'Kettlebell Skull Crusher'),
  ('kettlebell-squat', 'Kettlebell Squat'),
  ('kettlebell-sumo-deadlift', 'Kettlebell Sumo Deadlift'),
  ('kettlebell-sumo-high-pull', 'Kettlebell Sumo High Pull'),
  ('kettlebell-svend-press', 'Kettlebell Svend Press'),
  ('kettlebell-swing', 'Kettlebell Swing'),
  ('kettlebell-swing-clean', 'Kettlebell Swing Clean'),
  ('kettlebell-turkish-get-ups', 'Kettlebell Turkish Get Ups'),
  ('kettlebell-windmills', 'Kettlebell Windmills'),
  ('kettlebell-wrist-curl', 'Kettlebell Wrist Curl'),
  ('knee-push-ups', 'Knee Push Ups'),
  ('knee-to-chest-stretch', 'Knee-to-Chest Stretch'),
  ('kneeling-cable-row', 'Kneeling Cable Row'),
  ('kneeling-hip-flexor-stretch', 'Kneeling Hip Flexor Stretch'),
  ('kneeling-wrist-stretch', 'Kneeling Wrist Stretch'),
  ('l-sit', 'L Sit'),
  ('landmine-press', 'Landmine Press'),
  ('lat-pulldown', 'Lat Pulldown'),
  ('lateral-raise', 'Dumbbell Lateral Raise'),
  ('leg-curl', 'Lying Leg Curl'),
  ('leg-extension', 'Leg Extension'),
  ('leg-press', 'Leg Press'),
  ('legs-up-the-wall', 'Legs-Up-the-Wall Pose'),
  ('lizard-stretch', 'Lizard Stretch'),
  ('locust-pose', 'Locust Pose'),
  ('low-lunge', 'Low Lunge'),
  ('low-lunge-to-half-split', 'Low Lunge to Half Split'),
  ('lunge', 'Lunge'),
  ('lying-leg-raise', 'Lying Leg Raise'),
  ('lying-tricep-extension', 'Lying Tricep Extension'),
  ('machine-back-extension', 'Machine Back Extension'),
  ('machine-bicep-curl', 'Machine Bicep Curl'),
  ('machine-calf-raise', 'Machine Calf Raise'),
  ('machine-chest-fly', 'Machine Chest Fly'),
  ('machine-preacher-curl', 'Machine Preacher Curl'),
  ('machine-seated-crunch', 'Machine Seated Crunch'),
  ('machine-shoulder-press', 'Machine Shoulder Press'),
  ('machine-triceps-extension', 'Machine Triceps Extension'),
  ('medicine-ball-slam', 'Medicine Ball Slam'),
  ('mountain-climbers', 'Mountain Climbers'),
  ('mountain-pose', 'Mountain Pose'),
  ('muscle-snatch', 'Muscle Snatch'),
  ('muscle-ups', 'Muscle Ups'),
  ('neck-side-stretch', 'Neck Side Stretch'),
  ('negative-pull-ups', 'Negative Pull Ups'),
  ('neutral-grip-pull-ups', 'Neutral Grip Pull Ups'),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl'),
  ('ohp', 'Barbell Overhead Press'),
  ('one-arm-dumbbell-push-press', 'One-Arm Dumbbell Push Press'),
  ('one-arm-dumbbell-swing', 'One-Arm Dumbbell Swing'),
  ('one-arm-kettlebell-bicep-curl', 'One Arm Kettlebell Bicep Curl'),
  ('one-arm-kettlebell-bottoms-up-press', 'One-Arm Kettlebell Bottoms-Up Press'),
  ('one-arm-kettlebell-floor-glute-bridge-press', 'One Arm Kettlebell Floor Glute Bridge Press'),
  ('one-arm-kettlebell-floor-press', 'One Arm Kettlebell Floor Press'),
  ('one-arm-kettlebell-front-squat', 'One Arm Kettlebell Front Squat'),
  ('one-arm-kettlebell-push-press', 'One Arm Kettlebell Push Press'),
  ('one-arm-kettlebell-row', 'One Arm Kettlebell Row'),
  ('one-arm-kettlebell-shoulder-press', 'One Arm Kettlebell Shoulder Press'),
  ('one-arm-kettlebell-swing', 'One Arm Kettlebell Swing'),
  ('one-arm-kettlebell-tricep-kickback', 'One-Arm Kettlebell Tricep Kickback'),
  ('one-arm-landmine-press', 'One-Arm Landmine Press'),
  ('one-arm-lat-pulldown', 'One-Arm Lat Pulldown'),
  ('one-arm-single-leg-dumbbell-romanian-deadlift', 'One-Arm Single-Leg Dumbbell Romanian Deadlift'),
  ('one-arm-single-leg-kettlebell-romanian-deadlift', 'One-Arm Single-Leg Kettlebell Romanian Deadlift'),
  ('overhead-squat', 'Overhead Squat'),
  ('overhead-tricep-extension', 'Overhead Tricep Extension'),
  ('overhead-triceps-stretch', 'Overhead Triceps Stretch'),
  ('pause-deadlift', 'Pause Deadlift'),
  ('pause-pull-up', 'Pause Pull-Up'),
  ('pause-squat', 'Pause Squat'),
  ('paused-bench-press', 'Paused Bench Press'),
  ('paused-incline-bench-press', 'Paused Incline Bench Press'),
  ('paused-ohp', 'Paused Overhead Press'),
  ('pec-deck', 'Pec Deck'),
  ('pendlay-row', 'Pendlay Row'),
  ('pigeon-stretch', 'Pigeon Stretch'),
  ('pike-push-ups', 'Pike Push Ups')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('pilates-kneeling-side-kick', 'Pilates Kneeling Side Kick'),
  ('pilates-leg-pull-back', 'Pilates Leg Pull Back'),
  ('pilates-leg-pull-front', 'Pilates Leg Pull Front'),
  ('pilates-roll-down', 'Pilates Roll Down'),
  ('pilates-roll-over', 'Pilates Roll Over'),
  ('pilates-saw', 'Pilates Saw'),
  ('pilates-side-bend', 'Pilates Side Bend'),
  ('pilates-spine-stretch-forward', 'Pilates Spine Stretch Forward'),
  ('pilates-spine-twist', 'Pilates Spine Twist'),
  ('pistol-squat', 'Pistol Squat'),
  ('planche', 'Planche'),
  ('plank', 'Plank'),
  ('plate-loaded-donkey-calf-raise', 'Plate-Loaded Donkey Calf Raise'),
  ('plate-loaded-glute-drive', 'Plate-Loaded Glute Drive'),
  ('plate-loaded-lateral-raise', 'Plate-Loaded Lateral Raise'),
  ('plate-loaded-shrug', 'Plate-Loaded Shrug'),
  ('plate-pinch', 'Plate Pinch'),
  ('plate-pullover', 'Plate Pullover'),
  ('plow-pose', 'Plow Pose'),
  ('plyo-lunge', 'Plyo Lunge'),
  ('plyo-push-up', 'Plyo Push-Up'),
  ('preacher-curl', 'Preacher Curl'),
  ('preacher-hammer-curl', 'Preacher Hammer Curl'),
  ('pseudo-planche-push-ups', 'Pseudo Planche Push Ups'),
  ('pull-up', 'Pull-Up'),
  ('puppy-pose', 'Puppy Pose'),
  ('push-jerk', 'Push Jerk'),
  ('push-press', 'Push Press'),
  ('push-up', 'Push-Up'),
  ('pyramid-pose', 'Pyramid Pose'),
  ('rack-pull', 'Rack Pull'),
  ('rear-delt-fly', 'Rear Delt Fly'),
  ('reverse-crunches', 'Reverse Crunches'),
  ('reverse-curl', 'Reverse Curl'),
  ('reverse-grip-bent-over-row', 'Reverse Grip Bent Over Row'),
  ('reverse-grip-lat-pulldown', 'Reverse Grip Lat Pulldown'),
  ('reverse-lunge', 'Reverse Lunge'),
  ('reverse-nordic-curl', 'Reverse Nordic Curl'),
  ('reverse-plank', 'Reverse Plank'),
  ('reverse-plank-dips', 'Reverse Plank Dips'),
  ('reverse-tabletop-hip-pulses', 'Reverse Tabletop Hip Pulses'),
  ('reverse-tabletop-hold', 'Reverse Tabletop Hold'),
  ('revolved-chair-pose', 'Revolved Chair Pose'),
  ('revolved-crescent-lunge', 'Revolved Crescent Lunge'),
  ('ring-dead-hang', 'Ring Dead Hang'),
  ('ring-dips', 'Ring Dips'),
  ('ring-face-pull', 'Ring Face Pull'),
  ('ring-muscle-up', 'Ring Muscle-Up'),
  ('ring-push-up', 'Ring Push-Up'),
  ('ring-row', 'Ring Row'),
  ('rings-inverted-row', 'Rings Inverted Row'),
  ('romanian-deadlift', 'Romanian Deadlift'),
  ('rope-climb', 'Rope Climb'),
  ('rowing-machine', 'Rowing Machine'),
  ('running', 'Running'),
  ('russian-twist', 'Russian Twist'),
  ('savasana', 'Corpse Pose'),
  ('scapular-pull-ups', 'Scapular Pull Ups'),
  ('scissor-kicks', 'Scissor Kicks'),
  ('seated-barbell-overhead-press', 'Seated Barbell Overhead Press'),
  ('seated-cable-row', 'Seated Cable Row'),
  ('seated-calf-raise', 'Seated Calf Raise'),
  ('seated-db-press', 'Seated Dumbbell Shoulder Press'),
  ('seated-dumbbell-curl', 'Seated Dumbbell Curl'),
  ('seated-dumbbell-lateral-raise', 'Seated Dumbbell Lateral Raise'),
  ('seated-dumbbell-tricep-extension', 'Seated Dumbbell Tricep Extension'),
  ('seated-forward-fold', 'Seated Forward Fold'),
  ('seated-leg-curl', 'Seated Leg Curl'),
  ('seated-smith-machine-shoulder-press', 'Seated Smith Machine Shoulder Press'),
  ('seated-spinal-twist', 'Seated Spinal Twist'),
  ('seated-straddle-stretch', 'Seated Straddle Stretch'),
  ('shrug', 'Barbell Shrug'),
  ('side-lunge', 'Side Lunge'),
  ('side-lying-hip-abduction', 'Side-Lying Hip Abduction'),
  ('side-lying-hip-abduction-hold', 'Side-Lying Hip Abduction Hold'),
  ('side-lying-hip-adduction', 'Side Lying Hip Adduction'),
  ('side-lying-hip-adduction-hold', 'Side-Lying Hip Adduction Hold'),
  ('side-lying-lateral-raise', 'Side-Lying Lateral Raise'),
  ('side-plank', 'Side Plank'),
  ('side-plank-leg-lift', 'Side Plank with Leg Lift'),
  ('side-plank-leg-lift-hold', 'Side Plank Leg Lift Hold'),
  ('single-arm-chest-supported-dumbbell-row', 'Single-Arm Chest-Supported Dumbbell Row'),
  ('single-arm-db-row', 'Single-Arm Dumbbell Row'),
  ('single-arm-dumbbell-overhead-tricep-extension', 'Single-Arm Dumbbell Overhead Tricep Extension'),
  ('single-arm-hammer-curl', 'Single-Arm Hammer Curl'),
  ('single-arm-machine-shoulder-press', 'Single-Arm Machine Shoulder Press'),
  ('single-arm-plate-loaded-lateral-raise', 'Single-Arm Plate-Loaded Lateral Raise'),
  ('single-arm-tricep-pushdown', 'Single Arm Tricep Pushdown'),
  ('single-db-svend-press', 'Single Dumbbell Svend Press'),
  ('single-leg-calf-raise', 'Single Leg Calf Raise'),
  ('single-leg-extension', 'Single Leg Extension'),
  ('single-leg-glute-bridge', 'Single Leg Glute Bridge'),
  ('single-leg-glute-bridge-hold', 'Single-Leg Glute Bridge Hold'),
  ('single-leg-lying-leg-curl', 'Single Leg Lying Leg Curl'),
  ('single-leg-press', 'Single Leg Press'),
  ('single-leg-romanian-deadlift', 'Single Leg Romanian Deadlift'),
  ('sit-ups', 'Sit-Ups'),
  ('skull-crusher', 'Skull Crusher'),
  ('sled-row', 'Sled Row'),
  ('smith-machine-bench-press', 'Smith Machine Bench Press')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('smith-machine-bent-over-row', 'Smith Machine Bent Over Row'),
  ('smith-machine-bulgarian-split', 'Smith Machine Bulgarian Split Squat'),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise'),
  ('smith-machine-decline-bench-press', 'Smith Machine Decline Bench Press'),
  ('smith-machine-front-squat', 'Smith Machine Front Squat'),
  ('smith-machine-good-morning', 'Smith Machine Good Morning'),
  ('smith-machine-hip-thrust', 'Smith Machine Hip Thrust'),
  ('smith-machine-incline-bench-press', 'Smith Machine Incline Bench Press'),
  ('smith-machine-rdl', 'Smith Machine Romanian Deadlift'),
  ('smith-machine-reverse-grip-bent-over-row', 'Smith Machine Reverse Grip Bent Over Row'),
  ('smith-machine-reverse-lunge', 'Smith Machine Reverse Lunge'),
  ('smith-machine-shoulder-press', 'Smith Machine Shoulder Press'),
  ('smith-machine-shrug', 'Smith Machine Shrug'),
  ('smith-machine-split-squat', 'Smith Machine Split Squat'),
  ('smith-machine-squat', 'Smith Machine Squat'),
  ('smith-machine-upright-row', 'Smith Machine Upright Row'),
  ('snatch', 'Snatch'),
  ('sphinx-pose', 'Sphinx Pose'),
  ('spider-curl', 'Spider Curl'),
  ('split-jerk', 'Split Jerk'),
  ('split-squat', 'Split Squat'),
  ('spoto-press', 'Spoto Press'),
  ('squat', 'Barbell Back Squat'),
  ('stability-ball-hip-bridge', 'Stability Ball Hip Bridge'),
  ('stability-ball-knee-tuck', 'Stability Ball Knee Tuck'),
  ('stability-ball-push-up', 'Stability Ball Push-Up'),
  ('stability-ball-push-up-hands-on-ball', 'Stability Ball Push-Up (Hands on Ball)'),
  ('stability-ball-wall-squat', 'Stability Ball Wall Squat'),
  ('stair-climber', 'Stair Climber'),
  ('standing-calf-raise', 'Standing Calf Raise'),
  ('standing-calf-stretch', 'Standing Calf Stretch'),
  ('standing-forward-fold', 'Standing Forward Fold'),
  ('standing-forward-fold-to-half-lift', 'Standing Forward Fold to Half Lift'),
  ('standing-quad-stretch', 'Standing Quad Stretch'),
  ('standing-side-bend', 'Standing Side Bend'),
  ('standing-side-bend-flow', 'Standing Side Bend Flow'),
  ('standing-split', 'Standing Split'),
  ('stationary-bike', 'Stationary Bike'),
  ('step-ups', 'Step Ups'),
  ('stiff-leg-deadlift', 'Stiff Leg Deadlift'),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown'),
  ('straight-bar-cable-front-raise', 'Straight-Bar Cable Front Raise'),
  ('straight-bar-dips', 'Straight Bar Dips'),
  ('strict-curl', 'Strict Curl'),
  ('suitcase-carry', 'Suitcase Carry'),
  ('sumo-deadlift', 'Sumo Deadlift'),
  ('sumo-squat', 'Sumo Squat'),
  ('superman', 'Superman'),
  ('supine-spinal-twist', 'Supine Spinal Twist'),
  ('supine-windshield-wipers', 'Supine Windshield Wipers'),
  ('supported-shoulderstand', 'Supported Shoulderstand'),
  ('svend-press', 'Svend Press'),
  ('t-bar-row', 'T-Bar Row'),
  ('thoracic-bridge', 'Thoracic Bridge'),
  ('thread-the-needle', 'Thread the Needle'),
  ('thread-the-needle-flow', 'Thread the Needle Flow'),
  ('three-legged-dog', 'Three-Legged Downward Dog'),
  ('thruster', 'Thruster'),
  ('toes-to-bar', 'Toes to Bar'),
  ('treadmill-running', 'Treadmill Running'),
  ('tree-pose', 'Tree Pose'),
  ('triangle-pose', 'Triangle Pose'),
  ('tricep-kickback', 'Dumbbell Tricep Kickback'),
  ('tricep-pushdown', 'Cable Tricep Pushdown'),
  ('trx-bicep-curl', 'TRX Bicep Curl'),
  ('trx-chest-press', 'TRX Chest Press'),
  ('trx-face-pull', 'TRX Face Pull'),
  ('trx-hamstring-curl', 'TRX Hamstring Curl'),
  ('trx-lunge', 'TRX Lunge'),
  ('trx-pistol-squat', 'TRX Pistol Squat'),
  ('trx-plank', 'TRX Plank'),
  ('trx-row', 'TRX Row'),
  ('trx-side-plank', 'TRX Side Plank'),
  ('trx-squat', 'TRX Squat'),
  ('trx-tricep-extension', 'TRX Triceps Extension'),
  ('trx-y-fly', 'TRX Y-Fly'),
  ('upright-row', 'Barbell Upright Row'),
  ('upward-dog', 'Upward-Facing Dog'),
  ('v-bar-lat-pulldown', 'V-Bar Lat Pulldown'),
  ('v-bar-tricep-pushdown', 'V-Bar Tricep Pushdown'),
  ('v-sit', 'V-Sit'),
  ('v-ups', 'V Ups'),
  ('walking', 'Walking'),
  ('walking-lunge', 'Walking Lunge'),
  ('wall-push-ups', 'Wall Push Ups'),
  ('wall-sit', 'Wall Sit'),
  ('warrior-one', 'Warrior I'),
  ('warrior-three', 'Warrior III'),
  ('warrior-two', 'Warrior II'),
  ('weighted-dips', 'Weighted Dips'),
  ('weighted-pull-up', 'Weighted Pull-Up'),
  ('weighted-wall-crunch', 'Weighted Wall Crunch'),
  ('wide-grip-bench-press', 'Wide-Grip Bench Press'),
  ('wide-grip-pull-ups', 'Wide Grip Pull Ups'),
  ('wide-grip-push-ups', 'Wide Grip Push Ups'),
  ('wide-grip-seated-cable-row', 'Wide Grip Seated Cable Row'),
  ('wide-legged-forward-fold', 'Wide-Legged Forward Fold'),
  ('wide-stance-leg-press', 'Wide-Stance Leg Press'),
  ('wrist-curl', 'Bilateral Dumbbell Wrist Curl'),
  ('wrist-roller', 'Wrist Roller')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';-- Backfill English alternate name (search + display) for RepDB-sourced exercises.

update public.exercises e
set alternate_names = array[v.name_en]
from (values
  ('zottman-curl', 'Zottman Curl')
) as v(slug, name_en)
where e.slug = v.slug and e.alternate_names = '{}';